# Development Environment Properties
server.port=8081

# Common application properties override or specific to dev
app.storage.initialDataPath=initial-data.txt

# Database connection for dev environment
database.driver=org.postgresql.Driver
database.url=jdbc:postgresql://localhost:5432/olympia_db_dev
database.username=postgres
database.password=postgres

# Hibernate configuration
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

# Logging configuration
logging.level.dev\.local\.olympia=DEBUG
logging.level.org\.springframework=WARN

# Actuator endpoints (if not defined in common application.properties)
management.endpoints.web.exposure.include=health,info,prometheus

# This name identifies the service in Eureka
spring.application.name=service-registry

# Pointing to the Discovery Service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin