spring.profiles.active=local
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

health.training-manager.url=http://localhost:8080/api/trainings/training-types
health.training-manager.timeout-ms=2000


app.storage.initialDataPath=initial-data.txt

# Basic Logback configuration (can be moved to logback.xml for more detail)
logging.level.dev.local.olympia=INFO
logging.level.org.springframework=WARN

# Database connection properties for PostgreSQL
database.driver=org.postgresql.Driver
database.url=jdbc:postgresql://localhost:5432/olympia_db
database.username=postgres
database.password=postgres

# Hibernate properties
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

# This name identifies the service in Eureka
spring.application.name=service-registry

# Pointing to the Discovery Service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/